# Generated by Django 2.2.10 on 2020-03-28 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0006_auto_20200328_1252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='consumption',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
