# Generated by Django 2.2.10 on 2020-03-27 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_account_teams'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='billing_address_line',
        ),
        migrations.RemoveField(
            model_name='account',
            name='billing_city',
        ),
        migrations.RemoveField(
            model_name='account',
            name='billing_country',
        ),
        migrations.RemoveField(
            model_name='account',
            name='billing_postcode',
        ),
        migrations.RemoveField(
            model_name='account',
            name='billing_state',
        ),
        migrations.RemoveField(
            model_name='account',
            name='billing_street',
        ),
        migrations.RemoveField(
            model_name='account',
            name='email',
        ),
        migrations.RemoveField(
            model_name='account',
            name='industry',
        ),
        migrations.RemoveField(
            model_name='account',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='account',
            name='website',
        ),
        migrations.AddField(
            model_name='account',
            name='price',
            field=models.FloatField(null=True),
        ),
    ]
