# Generated by Django 2.2.10 on 2020-03-28 12:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0007_auto_20200328_1820'),
        ('accounts', '0012_auto_20200328_1252'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='contact_name',
        ),
        migrations.RemoveField(
            model_name='account',
            name='contacts',
        ),
        migrations.AddField(
            model_name='account',
            name='contacts',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='account_contacts', to='contacts.Contact'),
        ),
        migrations.AlterField(
            model_name='account',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
